// generated by scripts/generateChainClients.js
export class SpecialPlanetToken {
  constructor(private chain: import("../../eth").Eth) {}

  approve = (to: string, tokenId: string | number, txOption?: {}) => {
    if (!this.chain.web3 || !this.chain.address) {
      throw new Error("not logined")
    }

    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" }
          ],
          name: "approve",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x095ea7b3"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.address }
    ).methods
      .approve(to, tokenId)
      .send(txOption)
  }

  gateway = (): Promise<string> => {
    if (!this.chain.web3 || !this.chain.address) {
      throw new Error("not logined")
    }

    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [],
          name: "gateway",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x116191b6"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.address }
    ).methods
      .gateway()
      .call()
  }

  tokensOfOwnerByIndex = (
    owner: string,
    index: string | number
  ): Promise<{ tokenIds: Array<string>; nextIndex: string }> => {
    if (!this.chain.web3 || !this.chain.address) {
      throw new Error("not logined")
    }

    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "index", type: "uint256" }
          ],
          name: "tokensOfOwnerByIndex",
          outputs: [
            { internalType: "uint256[]", name: "tokenIds", type: "uint256[]" },
            { internalType: "uint256", name: "nextIndex", type: "uint256" }
          ],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x4707f44f"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.address }
    ).methods
      .tokensOfOwnerByIndex(owner, index)
      .call()
  }

  depositToGateway = (id: string | number, txOption?: {}) => {
    if (!this.chain.web3 || !this.chain.address) {
      throw new Error("not logined")
    }

    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
          name: "depositToGateway",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x9267daba"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.address }
    ).methods
      .depositToGateway(id)
      .send(txOption)
  }
}
