// generated by scripts/generateChainData.js
export class InGameAsteriskController {
  constructor(private chain: import("../../loom").Loom) {}

  getAsterisks = (
    account: string
  ): Promise<{
    confirmedGold: string
    goldConfirmedAt: string
    ids: Array<string>
    ranks: Array<string>
    times: Array<string>
    coordinates: Array<string>
  }> => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [{ internalType: "address", name: "account", type: "address" }],
          name: "getAsterisks",
          outputs: [
            { internalType: "uint200", name: "confirmedGold", type: "uint200" },
            { internalType: "uint32", name: "goldConfirmedAt", type: "uint32" },
            { internalType: "uint64[]", name: "ids", type: "uint64[]" },
            { internalType: "uint8[]", name: "ranks", type: "uint8[]" },
            { internalType: "uint32[]", name: "times", type: "uint32[]" },
            { internalType: "int16[]", name: "coordinates", type: "int16[]" }
          ],
          payable: false,
          stateMutability: "view",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.InGameAsteriskController,
      { from: this.chain.callerAddress() }
    ).methods
      .getAsterisks(account)
      .call()
  }

  setAsterisks = (
    asteriskId: string | number,
    coordinateQs: Array<string | number>,
    coordinateRs: Array<string | number>,
    txOption?: {}
  ) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [
            { internalType: "uint16", name: "asteriskId", type: "uint16" },
            { internalType: "int16[]", name: "coordinateQs", type: "int16[]" },
            { internalType: "int16[]", name: "coordinateRs", type: "int16[]" }
          ],
          name: "setAsterisks",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.InGameAsteriskController,
      { from: this.chain.callerAddress() }
    ).methods
      .setAsterisks(asteriskId, coordinateQs, coordinateRs)
      .send(txOption)
  }

  rankupAsterisks = (
    userInGameAsteriskIds: Array<string | number>,
    targetRanks: Array<string | number>,
    txOption?: {}
  ) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [
            { internalType: "uint64[]", name: "userInGameAsteriskIds", type: "uint64[]" },
            { internalType: "uint8[]", name: "targetRanks", type: "uint8[]" }
          ],
          name: "rankupAsterisks",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.InGameAsteriskController,
      { from: this.chain.callerAddress() }
    ).methods
      .rankupAsterisks(userInGameAsteriskIds, targetRanks)
      .send(txOption)
  }

  removeAsterisks = (userInGameAsteriskIds: Array<string | number>, txOption?: {}) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [{ internalType: "uint64[]", name: "userInGameAsteriskIds", type: "uint64[]" }],
          name: "removeAsterisks",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.InGameAsteriskController,
      { from: this.chain.callerAddress() }
    ).methods
      .removeAsterisks(userInGameAsteriskIds)
      .send(txOption)
  }

  claimInitialGold = (txOption?: {}) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [],
          name: "claimInitialGold",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.InGameAsteriskController,
      { from: this.chain.callerAddress() }
    ).methods
      .claimInitialGold()
      .send(txOption)
  }
}
