// generated by scripts/generateChainData.js
export class SpecialPlanetToken {
  constructor(private chain: import("../../loom").Loom) {}

  approve = (to: string, tokenId: string | number, txOption?: {}) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" }
          ],
          name: "approve",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .approve(to, tokenId)
      .send(txOption)
  }

  balanceOf = (owner: string): Promise<string> => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [{ internalType: "address", name: "owner", type: "address" }],
          name: "balanceOf",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .balanceOf(owner)
      .call()
  }

  gateway = (): Promise<string> => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [],
          name: "gateway",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          payable: false,
          stateMutability: "view",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .gateway()
      .call()
  }

  isApprovedForAll = (owner: string, operator: string): Promise<boolean> => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "address", name: "operator", type: "address" }
          ],
          name: "isApprovedForAll",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          payable: false,
          stateMutability: "view",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .isApprovedForAll(owner, operator)
      .call()
  }

  setApprovalForAll = (to: string, approved: boolean, txOption?: {}) => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "bool", name: "approved", type: "bool" }
          ],
          name: "setApprovalForAll",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .setApprovalForAll(to, approved)
      .send(txOption)
  }

  tokensOfOwnerByIndex = (
    owner: string,
    startIndex: string | number,
    endIndex: string | number
  ): Promise<Array<string>> => {
    return new this.chain.web3.eth.Contract(
      [
        {
          constant: true,
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "startIndex", type: "uint256" },
            { internalType: "uint256", name: "endIndex", type: "uint256" }
          ],
          name: "tokensOfOwnerByIndex",
          outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
          payable: false,
          stateMutability: "view",
          type: "function"
        }
      ],
      this.chain.env.contractAddresses.SpecialPlanetToken,
      { from: this.chain.callerAddress() }
    ).methods
      .tokensOfOwnerByIndex(owner, startIndex, endIndex)
      .call()
  }
}
